export const ENV = {
  NEXT_PUBLIC_WEBSITE_URL: process.env.NEXT_PUBLIC_WEBSITE_URL || 'http://localhost:3000',
  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: '',

  EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || '',
  EMAILJS_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || '',
  EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || '',

  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET || 'a42a36160dd751de17f70ae6c46e4f9b018cd6d3',
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID || 'f27de482fdeea6e87b88',
  NEXTAUTH_SECRET: 't2UHEJWq1Y6YXPYBcdAdj3GcJzWChrNOLG4bWHvB3og=',

  NODE_ENV: process.env.NODE_ENV || 'development'
}
