import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wiscaksono - About",
  description: "Generated by create next app",
};

export default function About() {
  return null;
}
