import { Metadata } from "next";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import AsideLink from "@/components/ui/aside-link";
import { FaRegEnvelope } from "react-icons/fa";
import { BsWhatsapp, BsInstagram, BsLinkedin } from "react-icons/bs";
import { TbBrandUpwork } from "react-icons/tb";

const data = [
  {
    title: "Contact",
    list: [
      {
        title: "Email",
        href: "mailto:wwicaksono96@gmail.com",
        icon: <FaRegEnvelope className="w-4 h-4" />,
      },
      {
        title: "Upwork",
        href: "https://www.upwork.com/freelancers/~01df34d78e05fa69bf",
        icon: <TbBrandUpwork className="w-4 h-4" />,
      },
      {
        title: "WhatsApp",
        href: "https://wa.me/+6287885002327",
        icon: <BsWhatsapp className="w-4 h-4" />,
      },
      {
        title: "LinkedIn",
        href: "https://www.linkedin.com/in/wiscaksono/",
        icon: <BsLinkedin className="w-4 h-4" />,
      },
      {
        title: "Instagram",
        href: "https://www.instagram.com/amachoker/",
        icon: <BsInstagram className="w-4 h-4" />,
      },
    ],
  },
];

export const metadata: Metadata = {
  title: "Wiscaksono - Contacts",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="grid grid-cols-12 overflow-hidden">
      <aside className="col-span-2 border-r border-lines">
        <Accordion type="single" collapsible defaultValue="item-0">
          {data.map((item, i) => (
            <AccordionItem value={`item-${i}`} key={i}>
              <AccordionTrigger>{item.title}</AccordionTrigger>
              <AccordionContent>
                <ul className="space-y-2">
                  {item.list.map((listItem, j) => (
                    <AsideLink
                      href={listItem.href}
                      key={j}
                      startWith="/about"
                      target="_blank"
                    >
                      {listItem.icon}
                      {listItem.title}
                    </AsideLink>
                  ))}
                </ul>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </aside>
      <section className="col-span-10 overflow-y-auto">{children}</section>
    </section>
  );
}
