import "./globals.css";
import { Fira_Code } from "next/font/google";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { TailwindIndicator } from "@/components/TailwindIndicator";
import { AnalyticsWrapper } from "@/components/Analytics";

import "@code-hike/mdx/dist/index.css";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Wiscaksono",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={firaCode.className}>
        <main>
          <Navbar />
          {children}
          <Footer />
        </main>
        <TailwindIndicator />
        <AnalyticsWrapper />
      </body>
    </html>
  );
}
