import { Metadata } from "next";
import Gear from "../../content/gear.mdx";

export const metadata: Metadata = {
  title: "Wiscaksono - Gear",
  description: "Generated by create next app",
};

export default function AboutGear() {
  return <Gear />;
}
